# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true  # default is true

contact_links:
  - name: SISAP 2025 Indexing challenge
    url: https://sisap-challenges.github.io/
    about: General information about the SISAP challenge, tasks, important dates, datasets, etc. 
  - name: SISAP web site
    url: https://sisap.org
    about: SISAP web site
