---
name: Others
description: Generic issues
title: Others
labels: Others

body:
- type: markdown
  attributes:
    value: Please describe the issue and how can be reproduced.

- type: input
  attributes:
    label: team
    description: Enter the name of your team
  validations:
    required: true

- type: input
  attributes:
    label: task
    description: Enter the list of tasks of your interest
  validations:
    required: false

- type: textarea
  attributes:
    label: issue
    description: Your issue
  validations:
    required: true

...
