---
name: Pre-registration request
description: Expression of interest in some of the Tasks of the SISAP 2025 challenge.
title: Pre-registration request
labels: Pre-registration request

body:
- type: markdown
  attributes:
    value: |
      Expression of interest
        - Task lists in the [challenge site](https://sisap-challenges.github.io/2025/tasks/)

- type: input
  attributes:
    label: team
    description: Enter the name of your team
  validations:
    required: true

- type: input
  attributes:
    label: corresponding
    description: Enter the GitHub username of your corresponding author
  validations:
    required: true

- type: input
  attributes:
    label: tasks
    description: Enter the list of tasks of your interest
  validations:
    required: true

- type: textarea
  attributes:
    label: members
    description: |
      Enter the initial members of your team
      - One member per line, affiliations
  validations:
    required: true


#- type: checkboxes
#  attributes:
#    label: open source
#    description: |
#      are you willing to open source your solution?
#    options:
#    - label: Yes
#      required: true

- type: markdown
  attributes:
    value: |
      You can follow this repository to be informed of any changes and news

...
